#cloud-config
package_update: true
package_upgrade: true

autoinstall:
  version: 1
  refresh-installer:
    update: yes
  locale: en_US.UTF-8
  keyboard:
    layout: us
    variant: ""
  identity:
    hostname: ubuntu
    username: administrator
    # Thay thế giá trị password bên dưới bằng mật khẩu băm thực của "Itadmin@2023"
    password: "$6$rounds=4096$e5aK6z1BjM.$LhpZtN1SyC9OIE31Z/h5RSJUvwdXj0S2vGqyOkM5bbU80Ea4aXEu6UTKOqaFQwWzBQG/5Y9NXN1Vg/K0hmUUV1"
  ssh:
    install-server: true
  storage:
    layout:
      name: lvm
  packages:
    - docker.io
    - docker-compose
    - git
    - nano

runcmd:
  - apt-get update
  - apt-get upgrade -y
