#cloud-config
autoinstall:
  version: 1
  refresh-installer:
    update: yes
  locale: en_US.UTF-8
  keyboard:
    layout: us
    variant: ""
  identity:
    hostname: ubuntu-auto
    username: administrator
    # Thay thế giá trị password bên dưới bằng mật khẩu băm của "Itadmin@2023"
    password: "$6$rounds=4096$YOUR_GENERATED_HASH_HERE"
  ssh:
    install-server: true
  storage:
    layout:
      name: lvm
  packages:
    - docker.io
    - docker-compose
    - git
    - nano

  # late-commands sẽ chạy sau khi cài đặt xong, nhưng trước khi kết thúc quá trình autoinstall
  late-commands:
    - curtin in-target --target=/target apt-get update
    - curtin in-target --target=/target apt-get upgrade -y
